sured/logger/models.py
from ..models import db

class AccountCreation(db.Model):
    __tablename__ = 'account_creations'
    id = db.Column(db.Integer, primary_key=True)
    account_id = db.Column(db.Integer)

class PostCreation(db.Model):
    __tablename__ = 'post_creations'
    id = db.Column(db.Integer, primary_key=True)
    post_id = db.Column(db.Integer)

sured/main/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, TextAreaField, BooleanField, SelectField,\
    SubmitField
from wtforms.validators import Required, Length, Email, Regexp
from wtforms import ValidationError
from flask.ext.pagedown.fields import PageDownField
from ..models import Role, User


class NameForm(Form):
    name = StringField('What is your name?', validators=[Required()])
    submit = SubmitField('Submit')


class EditProfileForm(Form):
    name = StringField('Full name', validators=[Length(0, 64)])
    location = StringField('Location', validators=[Length(0, 64)])
    bio = TextAreaField('Bio')
    submit = SubmitField('Submit')


class EditProfileAdminForm(Form):
    email = StringField('Email', validators=[Required(), Length(1, 64),
                                             Email()])
    username = StringField('Username', validators=[
        Required(), Length(1, 64), Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0,
                                          'Usernames must have only letters, '
                                          'numbers, dots or underscores')])
    confirmed = BooleanField('Confirmed')
    role = SelectField('Role', coerce=int)
    name = StringField('Real name', validators=[Length(0, 64)])
    location = StringField('Location', validators=[Length(0, 64)])
    bio = TextAreaField('Bio')
    submit = SubmitField('Submit')

    def __init__(self, user, *args, **kwargs):
        super(EditProfileAdminForm, self).__init__(*args, **kwargs)
        self.role.choices = [(role.id, role.name)
                             for role in Role.query.order_by(Role.name).all()]
        self.user = user

    def validate_email(self, field):
        if field.data != self.user.email and \
                User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already registered.')

    def validate_username(self, field):
        if field.data != self.user.username and \
                User.query.filter_by(username=field.data).first():
            raise ValidationError('Username already in use.')


class PostForm(Form):
    title = StringField('Question Title', validators=[Required(), Length(1, 255)])
    body = TextAreaField("Question", validators=[Required()])
    submit = SubmitField('Submit')


class CommentForm(Form):
    body = TextAreaField("Your Answer", validators=[Required()])
    submit = SubmitField('Submit')

sured/__init__.py
from flask import Flask, render_template
from flask.ext.bootstrap import Bootstrap
from flask.ext.mail import Mail
from flask.ext.moment import Moment
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager
from config import config

bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    login_manager.init_app(app)

    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)

    from main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

sured/logger/__init__.py
from flask import Blueprint

logger = Blueprint('logger', __name__)

from . import signals,  models

sured/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors
from ..models import Permission

@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

sured/main/views.py
from datetime import datetime
from flask import render_template, session, redirect, url_for, flash, request, \
    current_app, make_response, abort
from . import main
from ..models import User, Role, Permission, Post, Comment, post_saved
from .forms import EditProfileForm, EditProfileAdminForm, PostForm,\
     CommentForm
from .. import db
from ..decorators import admin_required, permission_required
from flask.ext.login import login_required, current_user

@main.before_app_request
def before_request():
    if request.endpoint  != 'static':
        post_saved.send(current_app, request=request)

@main.route('/', methods=['GET', 'POST'])
def index():
    form = PostForm()
    if current_user.can(Permission.WRITE_ARTICLES) and \
            form.validate_on_submit():
        post = Post(title=form.title.data,
                    body=form.body.data,
                    author=current_user._get_current_object())
        db.session.add(post)
        return redirect(url_for('.index'))
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['SURED_POSTS_PER_PAGE'],
        error_out=False)
    posts = pagination.items
    return render_template('index.html', form=form, posts=posts,\
        pagination=pagination)

@main.route('/users/<username>', methods=['GET', 'POST'])
def user(username):
    form = PostForm()
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    else:
        if current_user.can(Permission.WRITE_ARTICLES) and \
                form.validate_on_submit():
            post = Post(title=form.body.data,
                        body=form.body.data,
                        author=current_user._get_current_object())
            db.session.add(post)
            return redirect(url_for('.user', username=user.username))

    posts = user.posts.order_by(Post.timestamp.desc()).all()
    return render_template('user.html', user=user, posts=posts,\
                            form=form)

@main.route('/follow/<username>')
@login_required
@permission_required(Permission.FOLLOW)
def follow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid User.', 'danger')
        return redirect(url_for('.index'))
    if current_user.is_following(user):
        flash('You are already following this user.', 'warning')
        return redirect(url_for('.user', username=username))
    current_user.follow(user)
    flash('You are now following %s.' % username, 'success')
    return redirect(url_for('.user', username=username))

@main.route('/unfollow/<username>')
@login_required
@permission_required(Permission.FOLLOW)
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid User.', 'danger')
        return redirect(url_for('.index'))
    if not current_user.is_following(user):
        flash('You are not following this user.', 'warning')
        return redirect(url_for('.user', username=username))
    current_user.unfollow(user)
    flash('You are no longer following %s.' % username, 'warning')
    return redirect(url_for('.user', username=username))

@main.route('/followers/<username>')
def followers(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid user.', 'danger')
        return redirect(url_for('.index'))
    page = request.args.get('page', 1, type=int)
    pagination=user.followers.paginate(
        page, per_page=current_app.config['SURED_FOLLOWERS_PER_PAGE'],
        error_out=False)
    follows = [{'user': item.follower, 'timestamp':item.timestamp}
                for item in pagination.items]
    return render_template('followers.html', user=user, title='Followers of',
                            endpoint='.followers', pagination=pagination,
                            follows=follows)

@main.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.bio = form.bio.data
        db.session.add(current_user)
        flash('Your Profile has been updated.', 'success')
        return redirect(url_for('.user', username=current_user.username))
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.bio.data = current_user.bio
    return render_template('edit_profile.html', form=form)

@main.route('/edit-profile/<int:id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_profile_admin(id):
    user = User.query.get_or_404(id)
    form = EditProfileAdminForm(user=user)
    if form.validate_on_submit():
        user.email = form.email.data
        user.username = form.username.data
        user.confirmed = form.confirmed.data
        user.role = Role.query.get(form.role.data)
        user.name = form.name.data
        user.bio = form.bio.data
        db.session.add(user)
        flash('The profile has been updated.', 'success')
        return redirect(url_for('.user', username=user.username))
    form.email.data = user.email
    form.username.data = user.username
    form.confirmed.data = user.confirmed
    form.role.data = user.role_id
    form.name.data = user.name
    form.location.data = user.location
    form.bio.data = user.bio
    return render_template('edit_profile.html', form=form, user=user)


@main.route('/questions/')
def posts():
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['SURED_POSTS_PER_PAGE'],
        error_out=False)
    posts = pagination.items
    return render_template('posts.html', posts=posts, pagination=pagination)

    
@main.route('/questions/<int:id>', methods=['GET', 'POST'])
def post(id):
    post = Post.query.get_or_404(id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(body=form.body.data,
                        post=post,
                        author=current_user._get_current_object())
        db.session.add(comment)
        flash('Your answer has been published.', 'success')
        return redirect(url_for('.post', id=post.id, page=-1))
    page = request.args.get('page', 1, type=int)
    if page == -1:
        page = (post.comments.count() - 1) / \
               current_app.config['SURED_COMMENTS_PER_PAGE'] + 1
    pagination = post.comments.order_by(Comment.timestamp.asc()).paginate(
        page, per_page=current_app.config['SURED_COMMENTS_PER_PAGE'],
        error_out=False)
    comments = pagination.items
    return render_template('post.html', posts=[post], form=form,
                            comments=comments, pagination=pagination)

@main.route('/questions/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    post = Post.query.get_or_404(id)
    if current_user != post.author and \
            not current_user.can(Permission.ADMINISTER):
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.body = form.body.data
        db.session.add(post)
        flash('Your post has been updated.', 'success')
        return redirect(url_for('.post', id=post.id))
    form.body.data = post.body
    return render_template('edit_post.html', form=form)

@main.route('/comments/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_comment(id):
    comment = Comment.query.get_or_404(id)
    if current_user != comment.author and \
            not current_user.can(Permission.ADMINISTER):
        abort(403)
    form = CommentForm()
    if form.validate_on_submit():
        comment.body = form.body.data
        db.session.add(comment)
        flash('Your answer has been modified', 'success')
        return redirect(url_for('.post', id=comment.post_id))
    form.body.data = comment.body
    return render_template('edit_comment.html', form=form)

@main.route('/comments/select/<int:id>')
@login_required
def select_answer(id):
    comment = Comment.query.get_or_404(id)
    if current_user != comment.post.author and \
            not current_user.can(Permission.ADMINISTER):
        abort(403)
    for c in comment.post.comments:
        if c.answer:
            c.answer = False
            db.session.add(comment)
    comment.answer = True
    db.session.add(comment)
    flash('Answer to question selected', 'success')
    return redirect(url_for('.post', id=comment.post_id))

@main.route('/unanswered/')
def unanswered():
    def find_with_zero_comments(posts):
        post_list = []
        for post in posts:
            if post.comments.count() == 0:
                post_list.append(post)
        return post_list
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.filter(Post.comments == None).order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['SURED_COMMENTS_PER_PAGE'],
        error_out=False)
    posts = pagination.items
    return render_template('posts.html', posts=posts, pagination=pagination)

@main.route('/help/')
def help():
    return render_template('help.html')

sured/templates/base.html
{% extends 'layout.html' %}
{% block nav %}
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand page-scroll" href="{{ url_for('main.index') }}">
                [Sured]
            </a>

        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-center">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
                <li><a href="{{ url_for('main.posts') }}">Questions</a></li>
                <li><a href="{{ url_for('main.unanswered') }}">Unanswered</a></li>
                <li><a href="{{ url_for('main.help') }}">Help</a></li>


            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.can(Permission.MODERATE_COMMENTS) %}
                <li><a href="">Moderate</a></li>
                {% endif %}
                {% if current_user.is_authenticated() %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-bell"></i> Notifications <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li><a href="#">Action</a></li>
                      {% with messages = get_flashed_messages(with_categories=true) %}
                      {% for category, message in messages %}
                      <div class="alert alert-{{category}}">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        {{ message }}
                    </div>
                    {% endfor %}
                    {% endwith %}
                    <li><a href="#">Something else here</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Nav header</li>
                    <li><a href="#">Separated link</a></li>
                    <li><a href="#">One more separated link</a></li>
                </ul>
            </li>
            <li><a href="{{ url_for('main.user', username=current_user.username) }}"><span class="capitalize"><i class="fa fa-user"></i> {{ current_user.username }}</span></a></li>
            <li><a href="{{ url_for('auth.logout') }}"><i class="fa fa-unlock"></i> Log out</a></li>
            {% else %}
            <li><a href="{{ url_for('auth.register') }}">Sign Up</a></li>
            <li><a href="{{ url_for('auth.login') }}"><i class="fa fa-lock"></i> Log in</a></li>
            {% endif %}
        </ul>
    </div>
</div>
</nav>
{% endblock %}
{% block content %}{% endblock %}

sured/templates/index.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}
{% block header %}
<header id="home-area">
	<div class="container">
		<div class="row">

			<div class="col-md-8 col-md-offset-2 col-sm-12 col-xs-12">
				<div class="home-content wow fadeInLeft" data-wow-duration="1s" data-wow-delay="0s">
					<h1>[Sured]</h1>
				</div>
			</div>
			<div class="col-md-4 col-md-offset-2 col-sm-4 col-xs-12">
				<span class="intro">
					<h3>[Sured] is an open question & answer site for professionals, students, consultants and customer service professionals.</h3>
				</span>
			</div>
			<div class="col-md-4 col-sm-6 col-xs-12">
				<div class="panel pane-default">
					<div class="panel-body">
						<h4>How it works</h4>
						<p>Anybody can ask a question.</p>
						<p>Anybody can answer.</p>
						<p>Best answers get voted to the top.</p>
					</div>
				</div>
			</div>
			<div class="col-md-8 col-md-offset-2 col-sm-12 col-xs-12">
				<form class="inline-form" role="search">
					<div class="form-group">
						<div class="input-group">
							<input type="text" class="form-control" placeholder="Search">
							<div class="input-group-btn" style="margin-top: -10px;"><button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button></div>
						</div>
					</div>
				</form>
			</div>
		</div>

		<div class="col-md-6 col-sm-6 col-xs-12">
			<div class="home-feature pull-right center-block wow bounceIn" data-wow-duration="1s" data-wow-delay="1s">
			</div>
		</div>

	</div>
</div>
</header>
{% endblock %}
{% block content %}
<div class="content-section-b">
	<div class="container">
		<div class="col-md-8 col-md-offset-2">
			<div class="row">
			{% with messages = get_flashed_messages(with_categories=true) %}
				{% for category, message in messages %}
				<div class="alert alert-{{category}}">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
					{{ message }}
				</div>
				{% endfor %}
			{% endwith %}
			</div>
		</div>
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<ul class="nav nav-tabs" role="tablist">
					<li role="presentation" {% if request.args.type == 'all' %} class="active"{% endif %}><a href="{{ url_for('main.index', type='all') }}">All</a></li>
					<li role="presentation" {% if request.args.type == 'featured' %} class="active"{% endif %}><a href="{{ url_for('main.index', type='featured') }}">Featured</a></li>
					<li role="presentation" {% if request.args.type == 'hot' %} class="active"{% endif %}><a href="{{ url_for('main.index', type='hot') }}">Hot</a></li>
					<li role="presentation" {% if request.args.type == 'week' %} class="active"{% endif %}><a href="{{ url_for('main.index', type='week') }}">Week</a></li>
					<li role="presentation" {% if request.args.type == 'month' %} class="active"{% endif %}><a href="{{ url_for('main.index', type='month') }}">Month</a></li>
					<li role="presentation" {% if request.args.type == 'ask' %} class="active"{% endif %}><a href="{{ url_for('main.index', type='ask') }}" class="btn btn-danger">Ask Your Question</a></li>	    
				</ul>
			</div>
			<div class="col-md-8 col-md-offset-2 top">
				{% include '_posts.html' %}
				<div class="pagination">
					<span>More? Click here for the <a href="{{ url_for('main.posts') }}">complete list of questions</a>.</span>
				</div>
			</div>
		</div>
	</div>
	<!-- /.container -->
</div>
<div class="content-section-a">
	<div class="container">
		{% if request.endpoint == 'main.index' and current_user.is_authenticated() %}
		<div class="col-md-6 col-md-offset-2">
		{{ wtf.quick_form(form) }}
		</div>
		{% endif %}
	</div>
</div>
{% endblock %}

sured/templates/layout.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<!--<![endif]-->
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}The professional question..[todo: Fix this] | Sured{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">
    {% block extrahead %}{% endblock %}
</head>
<body>
    {% block nav %}
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand page-scroll" href="{{ url_for('main.index') }}">
                    <img src="img/logo.png" alt="Sured">
                </a>

            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li><a class="page-scroll" href="{{ url_for('main.index') }}">Home</a>
                    </li>
                    <li><a class="page-scroll" href="#">Services</a>
                    </li>
                    <li><a class="page-scroll" href="#">Partners</a>
                    </li>
                    <li><a class="page-scroll" href="#">About Us</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% endblock %}
    {% block header %}
    {% endblock %}
    {% block content %}
    <section id="services" class="section text-center">
        <div class="container">
            <h2 class="section-title wow fadeIn">Services</h2>
            <div class="row">
                <div class="col-md-4 col-sm-6">
                    <div class="single-service text-center wow fadeInRight" data-wow-duration="1s" data-wow-delay="0s">
                        <div class="service-content text-left">
                            <i class="fa fa-desktop fa-3x"></i>
                            <h3>Web Design</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet odit amet repellendus, eum ipsum laboriosam.</p>
                            <a href="#">Learn More</a>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 col-sm-6">
                    <div class="single-service text-left wow fadeInRight" data-wow-duration="1s" data-wow-delay=".3s">
                        <div class="service-title">
                            <i class="fa fa-mobile-phone fa-3x"></i>
                        </div>
                        <div class="service-content">
                            <h3>Mobile Design</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet odit amet repellendus, eum ipsum laboriosam.</p>
                            <a href="#">Learn More</a>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 col-sm-6">
                    <div class="single-service text-left wow fadeInRight" data-wow-duration="1s" data-wow-delay=".6s">
                        <div class="service-title">
                            <i class="fa fa-code fa-3x"></i>
                        </div>
                        <div class="service-content">
                            <h3>Code</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet odit amet repellendus, eum ipsum laboriosam.</p>
                            <a href="#">Learn More</a>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 col-sm-6">
                    <div class="single-service text-left wow fadeInRight" data-wow-duration="1s" data-wow-delay=".9s">
                        <div class="service-title">
                            <i class="fa fa-shopping-cart fa-3x"></i>
                        </div>
                        <div class="service-content">
                            <h3>Ecommerce</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet odit amet repellendus, eum ipsum laboriosam.</p>
                            <a href="#">Learn More</a>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 col-sm-6">
                    <div class="single-service text-left wow fadeInRight" data-wow-duration="1s" data-wow-delay="1.2s">
                        <div class="service-title">
                            <i class="fa fa-cog fa-3x"></i>
                        </div>
                        <div class="service-content">
                            <h3>CMS</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet odit amet repellendus, eum ipsum laboriosam.</p>
                            <a href="#">Learn More</a>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 col-sm-6">
                    <div class="single-service text-left wow fadeInRight" data-wow-duration="1s" data-wow-delay="1.5s">
                        <div class="service-title">
                            <i class="fa fa-rocket fa-3x"></i>
                        </div>
                        <div class="service-content">
                            <h3>Web Application</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet odit amet repellendus, eum ipsum laboriosam.</p>
                            <a href="#">Learn More</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}
    {% block footer %}
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="footer-content text-right">
                        <p>&copy; Copyright 2015 Sured.</p>
                        <p> All Rights Reserved.</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    {% endblock %}
    <script src="{{ url_for('static', filename='js/vendor/jquery-1.10.2.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    {% block scripts %}
    {{ moment.include_moment() }}
    {% endblock %}
</body>
</html>

sured/templates/user.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf%}

{% block content %}
<div class="header">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2 col-sm-12 col-xs-12">
				<form class="inline-form" role="search">
					<div class="form-group">
						<div class="input-group">
							<input type="text" class="form-control" placeholder="Search">
							<div class="input-group-btn" style="margin-top: -10px;"><button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button></div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<div class="content-section-a">
	<div class="container">
		<div class="row">
			<div class="col-md-6">
				{% if current_user == user %}
				<h1>hi, {{ user.username }}</h1>
				{% endif %}
				<h2>{{ user.name }}</h2>
				<p>{{ user.location }}</p>
				<p>{{ user.bio }}</p>
			</div>
			<div class="col-md-6">
				<p><a href="#">{{ user.email }}</a></p>
				<p>member since {{ moment(user.created).format('L') }}</p>
				<p>last seen {{ moment(user.last_seen).fromNow() }}</p>
				<p>
					{% if user == current_user %}
					<a class="btn btn-default" href="{{url_for('.edit_profile') }}">Edit Profile</a>
					{% endif %}
					{% if current_user.is_administrator() %}
					<a class="btn btn-danger" href="{{ url_for('main.edit_profile_admin', id=user.id) }}">Edit Profile [Admin]</a>
					{% endif %}
				</p>
				{% if current_user.can(Permission.FOLLOW) and user != current_user %}
				{% if not current_user.is_following(user) %}
				<a href="{{ url_for('.follow', username=user.username) }}" class="btn btn-primary">Follow</a>
				{% else %}
				<a href="{{ url_for('.unfollow', username=user.username) }}" class="btn btn-default">Unfollow</a>
				{% endif %}
				{% endif %}

				<a href="{{ url_for('.followers', username=user.username) }}">
					Followers: <span class="badge">{{ user.followers.count() }}</span>
				</a>
				{% if current_user.is_authenticated() and user != current_user and
				user.is_following(current_user) %}
				| <span class="label label-default">Follows you</span>
				{% endif %}
			</div>
		</div>
	</div>
</div>
<div class="content-section-b">
	<div class="container">	
		<div class="col-md-8 col-md-offset-2">
			<div class="row">
				{% with messages = get_flashed_messages(with_categories=true) %}
				{% for category, message in messages %}
				<div class="alert alert-{{category}}">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
					{{ message }}
				</div>
				{% endfor %}
				{% endwith %}
			</div>
		</div>
		{% if current_user.is_authenticated() and current_user == user %}
		<div class="row">
			<div class="col-md-6">
				{{ wtf.quick_form(form) }}
				<hr/>
			</div>
		</div>
		{% endif %}
		<div class="row">
			<div class="col-md-8">
				{% include '_posts.html' %}
			</div>
		</div>
	</div>
</div>
{% endblock %}